[workspace]
# Cargo should not unify feature flags across dev-dependencies and build
# dependencies. This will be the default behavior in Rust 2021.
resolver = "2"

members = [
  "runtime",
  "package/common",
  "package/database",
  "package/config",
  "package/middleware",
  "package/jwt",
  "api/auth",
  "api/setup",
  "api/service",
  "proxy/common",
  "proxy/io",
  "proxy/proxy",
  "proxy/balance"
]