[package]
name = "easy-proxy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.4.0"
futures-util = { version = "0.3", default-features = false }
http-body-util = "0.1.0-rc.3"
hyper = { git = "https://github.com/hyperium/hyper", rve="53b8372", default-features = false, features = ["full"] }
pin-project-lite = "0.2.10"
tokio = { version = "1", features = ["full"] }
http = "0.2"
argh = "0.1.10"
surrealdb = { version="1.0.0-beta.9", features = ["kv-mem", "kv-rocksdb"]}
once_cell = "1.18.0"
serde = "1.0.176"
axum = "0.6.19"
serde_json = "1.0.104"

