[package]
name = "easy-proxy"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Easy Proxy, a simple proxy server designed to provide essential features for network traffic management and proxying."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.4.0"
hyper = { git="https://github.com/hyperium/hyper", rvc="8dfeb73", features = ["full"] }
tokio = { version = "1", features = ["full"] }
http = "0.2"
argh = "0.1.10"
surrealdb = { version="1.0.0-beta.9", features = ["kv-mem", "kv-rocksdb"]}
once_cell = "1.18.0"
serde = { version="1.0.176", features = ["derive"] }
serde_json = "1.0.104"
jsonwebtoken = "8.3.0"
geo = "0.26.0"
chrono = "0.4.26"
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
pin-project-lite = "0.2.11"
http-body-util = "0.1.0-rc.3"
futures = "0.3.28"
async-trait = "0.1.73"
futures-util = "0.3.28"
mimalloc = "0.1.37"
axum = "0.6.20"

[dev-dependencies]
ureq = "2.7.1"

[profile.release]
strip = true
opt-level = "z"  # Optimize for size.
lto = true
codegen-units = 1
panic = "abort"
