[package]
name = "easy-proxy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.4.0"
futures-util = { version = "0.3", default-features = false }
hyper = { version="0.14.27",  features = ["full"] }
tokio = { version = "1", features = ["full"] }
http = "0.2"
argh = "0.1.10"
surrealdb = { version="1.0.0-beta.9", features = ["kv-mem", "kv-rocksdb"]}
once_cell = "1.18.0"
serde = { version="1.0.176", features = ["derive"] }
axum = "0.6.19"
serde_json = "1.0.104"
tower = { version = "0.4.13", features = ["make", "util"] }
tower-http = { version="0.4.3", features = ["add-extension"] }
jsonwebtoken = "8.3.0"
geo = "0.26.0"
chrono = "0.4.26"
tokio-stream = { version="0.1.14", features = ["net"] }
futures = "0.3.28"
pin-project = "1.1.3"
tokio-util = {version="0.7.8", features = ["io"]}
async-trait = "0.1"
socket2 = "0.5.3"
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
httparse = "1.8.0"

