apiVersion: v1
kind: Pod
metadata:
  labels:
    run: easy-proxy
  name: easy-proxy
spec:
  containers:
    - args:
        - '--authen'
        - my_authen_key
        - '--host'
        - 0.0.0.0:8100
      command:
        - ./easy-proxy
      image: ghcr.io/aitthi/easy-proxy:latest
      imagePullPolicy: Always
      name: easy-proxy
      ports:
        - containerPort: 8100
          name: http
          protocol: TCP
      resources: {}
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
