[package]
name = "runtime"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
api_auth = { path = "../api/auth" }
api_setup = { path = "../api/setup" }
api_service = { path = "../api/service" }
common = { path = "../package/common" }
config = { path = "../package/config" }
database = { path = "../package/database" }
utoipa-swagger-ui = { version = "4", features = ["axum"] }