runtime:
  addr: "0.0.0.0:1337"
proxy:
  addr: "0.0.0.0:8088"
  max_open_connections: 20 # per destination
jwt:
  public: config/jwt/default_public.key
  private: config/jwt/default_private.key
  expire: 8h
database:
  engine: Speedb # Tikv or Speedb // case sensitive
  file: easy_proxy.db # only for Speedb
  host: "127.0.0.1:2379" # only for Tikv
  namespace: easy_proxy
  database: easy_proxy
